-- MySQL Script generated by MySQL Workbench
-- Sat Mar 22 22:18:25 2025
-- Model: tifosi    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tifosi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tifosi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tifosi` DEFAULT CHARACTER SET utf8 ;
USE `tifosi` ;

-- -----------------------------------------------------
-- Table `tifosi`.`ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tifosi`.`ingredient` (
  `id_ingredient` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_ingredient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tifosi`.`foccacia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tifosi`.`foccacia` (
  `id_foccacia` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  `prix` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`id_foccacia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tifosi`.`marque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tifosi`.`marque` (
  `id_marque` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_marque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tifosi`.`boisson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tifosi`.`boisson` (
  `id_boisson` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  `marque_id_marque` INT NOT NULL,
  PRIMARY KEY (`id_boisson`),
  INDEX `fk_boisson_marque1_idx` (`marque_id_marque` ASC) VISIBLE,
  CONSTRAINT `fk_boisson_marque1`
    FOREIGN KEY (`marque_id_marque`)
    REFERENCES `tifosi`.`marque` (`id_marque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tifosi`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tifosi`.`menu` (
  `id_menu` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  `prix` DECIMAL(5,2) NOT NULL,
  `boisson_id_boisson` INT NOT NULL,
  `foccacia_id_foccacia` INT NOT NULL,
  PRIMARY KEY (`id_menu`),
  INDEX `fk_menu_boisson1_idx` (`boisson_id_boisson` ASC) VISIBLE,
  INDEX `fk_menu_foccacia1_idx` (`foccacia_id_foccacia` ASC) VISIBLE,
  CONSTRAINT `fk_menu_boisson1`
    FOREIGN KEY (`boisson_id_boisson`)
    REFERENCES `tifosi`.`boisson` (`id_boisson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menu_foccacia1`
    FOREIGN KEY (`foccacia_id_foccacia`)
    REFERENCES `tifosi`.`foccacia` (`id_foccacia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tifosi`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tifosi`.`Client` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `code_postal` INT NOT NULL,
  PRIMARY KEY (`id_client`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tifosi`.`comprend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tifosi`.`comprend` (
  `foccacia_id_foccacia` INT NOT NULL,
  `ingredient_id_ingredient` INT NOT NULL,
  `quantite` INT NULL,
  PRIMARY KEY (`foccacia_id_foccacia`, `ingredient_id_ingredient`),
  INDEX `fk_foccacia_has_ingredient_ingredient1_idx` (`ingredient_id_ingredient` ASC) VISIBLE,
  INDEX `fk_foccacia_has_ingredient_foccacia1_idx` (`foccacia_id_foccacia` ASC) VISIBLE,
  CONSTRAINT `fk_foccacia_has_ingredient_foccacia1`
    FOREIGN KEY (`foccacia_id_foccacia`)
    REFERENCES `tifosi`.`foccacia` (`id_foccacia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_foccacia_has_ingredient_ingredient1`
    FOREIGN KEY (`ingredient_id_ingredient`)
    REFERENCES `tifosi`.`ingredient` (`id_ingredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tifosi`.`achete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tifosi`.`achete` (
  `menu_id_menu` INT NOT NULL,
  `Client_id_client` INT NOT NULL,
  `date_achat` DATE NOT NULL DEFAULT (NOW()),
  PRIMARY KEY (`menu_id_menu`, `Client_id_client`),
  INDEX `fk_menu_has_Client_Client1_idx` (`Client_id_client` ASC) VISIBLE,
  INDEX `fk_menu_has_Client_menu1_idx` (`menu_id_menu` ASC) VISIBLE,
  CONSTRAINT `fk_menu_has_Client_menu1`
    FOREIGN KEY (`menu_id_menu`)
    REFERENCES `tifosi`.`menu` (`id_menu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menu_has_Client_Client1`
    FOREIGN KEY (`Client_id_client`)
    REFERENCES `tifosi`.`Client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'tifosi' IDENTIFIED BY 'P@assw0rd';

GRANT ALL ON `tifosi`.* TO 'tifosi';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
